TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += flipprps.db
DATA += flipprps.proto

#=======================================
include $(TOP)/configure/RULES
